# Тестовые свойства для демонстрации работы глобальных свойств
global:
  propOne: value_global_prop_one_default_dev
  propTwo: value_global_prop_two_default_dev

# Настройки для eureka-client
eureka:
  instance:
      preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
