# Динамический порт
server:
  port: 0

spring:
  main:
    banner-mode: "off"

# Настройки для eureka-экземпляров
eureka:
  instance:
      instanceId: ${spring.application.name}:${random.value}:${spring.cloud.client.hostname}:${server.port}
      leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  eureka:
    enabled: true

# Адрес admin-сервера
spring:
  boot:
    admin:
      url: http://localhost:8080
      turbine:
        clusters: default
        location: turbine
      #routes:
      #  endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,activiti

# Для admin-сервера
# Для простого обновления конфигурации через post-сервис /refresh
management:
  security:
    enabled: false

######################################################
# Список имен сервисов
#####################################################
services:
  name:
    hello: hello
    account: account
    feigndemo: feigndemo


######################################################
# Список ресурсов
#####################################################
  resources:
    execute: execute