# Динамический порт
server:
  port: 0


# Настройки для eureka-экземпляров
eureka:
  instance:
      instanceId: ${spring.application.name}:${random.value}:${spring.cloud.client.hostname}:${server.port}
      leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 1000
  ConnectTimeout: 2500

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2500


# Для admin-сервера
# Для простого обновления конфигурации через post-сервис /refresh
management:
  security:
    enabled: false

######################################################
# Список имен сервисов
#####################################################
services:
  name:
    adminserver: admin-server
    hello: hello
    hellolong: hello-long
    account: account
    feigndemo: feigndemo


######################################################
# Список ресурсов
#####################################################
  resources:
    execute: execute