# Тестовые свойства для демонстрации работы глобальных свойств
global:
  propOne: value_global_prop_one_default6
  propTwo: value_global_prop_two_default6

# Настройки для eureka-client
eureka:
  instance:
      preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

