# Тестовые свойства для демонстрации работы глобальных свойств
global:
  propOne: value_global_prop_one_default_dev
  propTwo: value_global_prop_two_default_dev

# Настройки для eureka-экземпляров
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/