# Динамический порт
server:
  port: 0

spring:
  main:
    banner-mode: "off"

# Настройки для eureka-экземпляров
eureka:
  instance:
      instanceId: ${eureka.instance.appname}:${random.value}:${spring.cloud.client.hostname}:${server.port}
      leaseRenewalIntervalInSeconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  eureka:
    enabled: true

# Для простого обновления конфигурации через post-сервис /refresh
management:
  security:
    enabled: false

######################################################
# Список имен сервисов
#####################################################
services:
  name:
    hello: hello-service
    account: account
    feigndemo: feigndemo


######################################################
# Список ресурсов
#####################################################
  resources:
    execute: execute